### ISSUE TITLE
streamlit libtorchaudio.so error on MacOS

### ISSUE THREAD

**Issue by drnic** [ducanhdt/openai_whisper_finetuning#5]
After installing dependencies in #4, and running `streamlit` command from readme, I get the following error on my MacOS/M2:

```
$ streamlit run interface.py


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.10.26.23:8501

2022-12-01 07:42:37.427 Created a temporary directory at /var/folders/wd/xnncwqp96rj0v1y2nms64mq80000gn/T/tmp1yy21bts
2022-12-01 07:42:37.427 Writing /var/folders/wd/xnncwqp96rj0v1y2nms64mq80000gn/T/tmp1yy21bts/_remote_module_non_scriptable.py
2022-12-01 07:42:38.149 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
  File "/Users/drnic/Projects/mylocalcricket/openai_whisper_finetuning/interface.py", line 11, in <module>
    import torchaudio.transforms as at
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torchaudio/lib/libtorchaudio.so, 0x0006): Symbol not found: (__ZN2at4_ops15sum_dim_IntList4callERKNS_6TensorEN3c108ArrayRefIxEEbNS5_8optionalINS5_10ScalarTypeEEE)
  Referenced from: '/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torchaudio/lib/libtorchaudio.so'
  Expected in: '/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib'
```

**Comment by drnic** [comment]
Uninstalling `torchaudio` and reinstalling seems to pull down a better package:

```
$ pip3 uninstall torchaudio
Found existing installation: torchaudio 0.12.1
Uninstalling torchaudio-0.12.1:
  Would remove:
    /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torchaudio-0.12.1.dist-info/*
    /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/torchaudio/*
Proceed (Y/n)? y
  Successfully uninstalled torchaudio-0.12.1

$ pip3 install torchaudio
Collecting torchaudio
  Downloading torchaudio-0.13.0-cp39-cp39-macosx_12_0_arm64.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 14.7 MB/s
Requirement already satisfied: torch in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from torchaudio) (1.13.0)
Requirement already satisfied: typing-extensions in /opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages (from torch->torchaudio) (4.4.0)
Installing collected packages: torchaudio
Successfully installed torchaudio-0.13.0
```
